### ISSUE TITLE
500 Internal server error

### ISSUE THREAD

**Issue by hmhuan** [monodyle/codeleak#2]
When I tried the example which you shared in README file. the server api return 500
<img width="1466" alt="Screen Shot 2022-05-19 at 00 45 31" src="https://user-images.githubusercontent.com/10975154/169085791-c19a5fe2-0211-4492-9a81-e2b9bcb05f82.png">

**Comment by monodyle** [comment]
This issue happen because the database on supabase (free plan) was stopped due to the database not having any user connect for a long time. I think I won't support re-enable because it will continue to be disabled if there is no user. Sorry about that.
